name: Deploy to App Engine

on:
  push:
    branches: [work]

jobs:
  deploy:
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build
        run: |
          cd frontend && npm ci && npm run build
          cd ../backend && npm ci
      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Deploy
        run: gcloud app deploy --quiet
