name: Deploy to App Engine

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build
        run: |
          cd frontend && npm ci && npm run build
          cd ../backend && npm ci
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Ensure App Engine app
        run: |
          gcloud app describe --project="${{ secrets.GCP_PROJECT }}" > /dev/null 2>&1 || \
          gcloud app create --project="${{ secrets.GCP_PROJECT }}" --region="${{ secrets.GCP_REGION }}" --quiet
      - name: Deploy
        run: gcloud app deploy --quiet
